--------------------------------------------------------
--  파일이 생성됨 - 일요일-5월-19-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GROUPS
--------------------------------------------------------

  CREATE TABLE "HR"."GROUPS" 
   (	"GROUP_CODE" NUMBER, 
	"GROUP_NAME" VARCHAR2(200 BYTE), 
	"GROUP_TEL" VARCHAR2(15 BYTE), 
	"GROUP_IMG" BLOB, 
	"GROUP_LOCALCODE" NUMBER, 
	"GROUP_ADDRESS" VARCHAR2(50 BYTE), 
	"GROUP_HOMEPAGE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("GROUP_IMG") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into HR.GROUPS
SET DEFINE OFF;
Insert into HR.GROUPS (GROUP_CODE,GROUP_NAME,GROUP_TEL,GROUP_LOCALCODE,GROUP_ADDRESS,GROUP_HOMEPAGE) values (3,'니밥풀 중학교','02-112',0,'서울','naver.com');
Insert into HR.GROUPS (GROUP_CODE,GROUP_NAME,GROUP_TEL,GROUP_LOCALCODE,GROUP_ADDRESS,GROUP_HOMEPAGE) values (2,'바로메로나 고등학교','063-119',0,'서울','naver.com');
Insert into HR.GROUPS (GROUP_CODE,GROUP_NAME,GROUP_TEL,GROUP_LOCALCODE,GROUP_ADDRESS,GROUP_HOMEPAGE) values (9,'test','test',0,'서울','naver.com');
Insert into HR.GROUPS (GROUP_CODE,GROUP_NAME,GROUP_TEL,GROUP_LOCALCODE,GROUP_ADDRESS,GROUP_HOMEPAGE) values (5,'멘구 중학교','999-999',0,'서울','naver.com');
Insert into HR.GROUPS (GROUP_CODE,GROUP_NAME,GROUP_TEL,GROUP_LOCALCODE,GROUP_ADDRESS,GROUP_HOMEPAGE) values (4,'멘띠티 고등학교','002',0,'서울','naver.com');
Insert into HR.GROUPS (GROUP_CODE,GROUP_NAME,GROUP_TEL,GROUP_LOCALCODE,GROUP_ADDRESS,GROUP_HOMEPAGE) values (6,'하약스 고등학교','002-212',0,'서울 마포구','google.com');
Insert into HR.GROUPS (GROUP_CODE,GROUP_NAME,GROUP_TEL,GROUP_LOCALCODE,GROUP_ADDRESS,GROUP_HOMEPAGE) values (7,'또트넘 중학교','12121-1',0,'서울 합정','ffffuck.com');
Insert into HR.GROUPS (GROUP_CODE,GROUP_NAME,GROUP_TEL,GROUP_LOCALCODE,GROUP_ADDRESS,GROUP_HOMEPAGE) values (1,'레알마도리도 중학교','062-112',0,'서울특별시 강남구 청담동','naver.com');
Insert into HR.GROUPS (GROUP_CODE,GROUP_NAME,GROUP_TEL,GROUP_LOCALCODE,GROUP_ADDRESS,GROUP_HOMEPAGE) values (8,'육배투스 고등학교','999-999',0,'서울','naver.com');
--------------------------------------------------------
--  DDL for Index GROUPS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."GROUPS_PK" ON "HR"."GROUPS" ("GROUP_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table GROUPS
--------------------------------------------------------

  ALTER TABLE "HR"."GROUPS" ADD CONSTRAINT "GROUPS_PK" PRIMARY KEY ("GROUP_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."GROUPS" MODIFY ("GROUP_LOCALCODE" NOT NULL ENABLE);
  ALTER TABLE "HR"."GROUPS" MODIFY ("GROUP_NAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."GROUPS" MODIFY ("GROUP_CODE" NOT NULL ENABLE);
