--------------------------------------------------------
--  颇老捞 积己凳 - 老夸老-5岿-19-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PLAYER_PHYSICAL
--------------------------------------------------------

  CREATE TABLE "HR"."PLAYER_PHYSICAL" 
   (	"PLAYER_PHYSICAL_CODE" NUMBER, 
	"PLAYER_CODE" NUMBER, 
	"GROUP_CODE" NUMBER, 
	"PLAYER_PHYSICAL_SEX" NUMBER, 
	"PLAYER_PHYSICAL_AGE" NUMBER, 
	"PLAYER_PHYSICAL_HEIGHT" NUMBER, 
	"PLAYER_PHYSICAL_WEIGHT" NUMBER, 
	"PLAYER_PHYSICAL_LEFTFOOT" NUMBER, 
	"PLAYER_PHYSICAL_RIGHTFOOT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.PLAYER_PHYSICAL
SET DEFINE OFF;
Insert into HR.PLAYER_PHYSICAL (PLAYER_PHYSICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_PHYSICAL_SEX,PLAYER_PHYSICAL_AGE,PLAYER_PHYSICAL_HEIGHT,PLAYER_PHYSICAL_WEIGHT,PLAYER_PHYSICAL_LEFTFOOT,PLAYER_PHYSICAL_RIGHTFOOT) values (76,92,3,0,0,0,0,0,0);
Insert into HR.PLAYER_PHYSICAL (PLAYER_PHYSICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_PHYSICAL_SEX,PLAYER_PHYSICAL_AGE,PLAYER_PHYSICAL_HEIGHT,PLAYER_PHYSICAL_WEIGHT,PLAYER_PHYSICAL_LEFTFOOT,PLAYER_PHYSICAL_RIGHTFOOT) values (77,93,4,0,0,0,0,0,0);
Insert into HR.PLAYER_PHYSICAL (PLAYER_PHYSICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_PHYSICAL_SEX,PLAYER_PHYSICAL_AGE,PLAYER_PHYSICAL_HEIGHT,PLAYER_PHYSICAL_WEIGHT,PLAYER_PHYSICAL_LEFTFOOT,PLAYER_PHYSICAL_RIGHTFOOT) values (78,94,5,0,0,0,0,0,0);
Insert into HR.PLAYER_PHYSICAL (PLAYER_PHYSICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_PHYSICAL_SEX,PLAYER_PHYSICAL_AGE,PLAYER_PHYSICAL_HEIGHT,PLAYER_PHYSICAL_WEIGHT,PLAYER_PHYSICAL_LEFTFOOT,PLAYER_PHYSICAL_RIGHTFOOT) values (79,95,6,0,0,0,0,0,0);
Insert into HR.PLAYER_PHYSICAL (PLAYER_PHYSICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_PHYSICAL_SEX,PLAYER_PHYSICAL_AGE,PLAYER_PHYSICAL_HEIGHT,PLAYER_PHYSICAL_WEIGHT,PLAYER_PHYSICAL_LEFTFOOT,PLAYER_PHYSICAL_RIGHTFOOT) values (80,96,7,0,0,0,0,0,0);
Insert into HR.PLAYER_PHYSICAL (PLAYER_PHYSICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_PHYSICAL_SEX,PLAYER_PHYSICAL_AGE,PLAYER_PHYSICAL_HEIGHT,PLAYER_PHYSICAL_WEIGHT,PLAYER_PHYSICAL_LEFTFOOT,PLAYER_PHYSICAL_RIGHTFOOT) values (81,97,8,0,0,0,0,0,0);
Insert into HR.PLAYER_PHYSICAL (PLAYER_PHYSICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_PHYSICAL_SEX,PLAYER_PHYSICAL_AGE,PLAYER_PHYSICAL_HEIGHT,PLAYER_PHYSICAL_WEIGHT,PLAYER_PHYSICAL_LEFTFOOT,PLAYER_PHYSICAL_RIGHTFOOT) values (74,90,1,0,0,0,0,0,0);
Insert into HR.PLAYER_PHYSICAL (PLAYER_PHYSICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_PHYSICAL_SEX,PLAYER_PHYSICAL_AGE,PLAYER_PHYSICAL_HEIGHT,PLAYER_PHYSICAL_WEIGHT,PLAYER_PHYSICAL_LEFTFOOT,PLAYER_PHYSICAL_RIGHTFOOT) values (75,91,2,0,0,0,0,0,0);
Insert into HR.PLAYER_PHYSICAL (PLAYER_PHYSICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_PHYSICAL_SEX,PLAYER_PHYSICAL_AGE,PLAYER_PHYSICAL_HEIGHT,PLAYER_PHYSICAL_WEIGHT,PLAYER_PHYSICAL_LEFTFOOT,PLAYER_PHYSICAL_RIGHTFOOT) values (66,82,1,0,0,0,0,0,0);
Insert into HR.PLAYER_PHYSICAL (PLAYER_PHYSICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_PHYSICAL_SEX,PLAYER_PHYSICAL_AGE,PLAYER_PHYSICAL_HEIGHT,PLAYER_PHYSICAL_WEIGHT,PLAYER_PHYSICAL_LEFTFOOT,PLAYER_PHYSICAL_RIGHTFOOT) values (67,83,2,0,0,0,0,0,0);
Insert into HR.PLAYER_PHYSICAL (PLAYER_PHYSICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_PHYSICAL_SEX,PLAYER_PHYSICAL_AGE,PLAYER_PHYSICAL_HEIGHT,PLAYER_PHYSICAL_WEIGHT,PLAYER_PHYSICAL_LEFTFOOT,PLAYER_PHYSICAL_RIGHTFOOT) values (68,84,3,0,0,0,0,0,0);
Insert into HR.PLAYER_PHYSICAL (PLAYER_PHYSICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_PHYSICAL_SEX,PLAYER_PHYSICAL_AGE,PLAYER_PHYSICAL_HEIGHT,PLAYER_PHYSICAL_WEIGHT,PLAYER_PHYSICAL_LEFTFOOT,PLAYER_PHYSICAL_RIGHTFOOT) values (69,85,4,0,0,0,0,0,0);
Insert into HR.PLAYER_PHYSICAL (PLAYER_PHYSICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_PHYSICAL_SEX,PLAYER_PHYSICAL_AGE,PLAYER_PHYSICAL_HEIGHT,PLAYER_PHYSICAL_WEIGHT,PLAYER_PHYSICAL_LEFTFOOT,PLAYER_PHYSICAL_RIGHTFOOT) values (70,86,5,0,0,0,0,0,0);
Insert into HR.PLAYER_PHYSICAL (PLAYER_PHYSICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_PHYSICAL_SEX,PLAYER_PHYSICAL_AGE,PLAYER_PHYSICAL_HEIGHT,PLAYER_PHYSICAL_WEIGHT,PLAYER_PHYSICAL_LEFTFOOT,PLAYER_PHYSICAL_RIGHTFOOT) values (71,87,6,0,0,0,0,0,0);
Insert into HR.PLAYER_PHYSICAL (PLAYER_PHYSICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_PHYSICAL_SEX,PLAYER_PHYSICAL_AGE,PLAYER_PHYSICAL_HEIGHT,PLAYER_PHYSICAL_WEIGHT,PLAYER_PHYSICAL_LEFTFOOT,PLAYER_PHYSICAL_RIGHTFOOT) values (72,88,7,0,0,0,0,0,0);
Insert into HR.PLAYER_PHYSICAL (PLAYER_PHYSICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_PHYSICAL_SEX,PLAYER_PHYSICAL_AGE,PLAYER_PHYSICAL_HEIGHT,PLAYER_PHYSICAL_WEIGHT,PLAYER_PHYSICAL_LEFTFOOT,PLAYER_PHYSICAL_RIGHTFOOT) values (73,89,8,0,0,0,0,0,0);
--------------------------------------------------------
--  DDL for Index PLAYER_PHYSICAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."PLAYER_PHYSICAL_PK" ON "HR"."PLAYER_PHYSICAL" ("PLAYER_PHYSICAL_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PLAYER_PHYSICAL
--------------------------------------------------------

  ALTER TABLE "HR"."PLAYER_PHYSICAL" ADD CONSTRAINT "PLAYER_PHYSICAL_PK" PRIMARY KEY ("PLAYER_PHYSICAL_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."PLAYER_PHYSICAL" MODIFY ("PLAYER_PHYSICAL_RIGHTFOOT" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_PHYSICAL" MODIFY ("PLAYER_PHYSICAL_LEFTFOOT" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_PHYSICAL" MODIFY ("PLAYER_PHYSICAL_WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_PHYSICAL" MODIFY ("PLAYER_PHYSICAL_HEIGHT" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_PHYSICAL" MODIFY ("PLAYER_PHYSICAL_AGE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_PHYSICAL" MODIFY ("PLAYER_PHYSICAL_SEX" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_PHYSICAL" MODIFY ("GROUP_CODE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_PHYSICAL" MODIFY ("PLAYER_CODE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_PHYSICAL" MODIFY ("PLAYER_PHYSICAL_CODE" NOT NULL ENABLE);
