--------------------------------------------------------
--  颇老捞 积己凳 - 老夸老-5岿-19-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PLAYER_TEACHER
--------------------------------------------------------

  CREATE TABLE "HR"."PLAYER_TEACHER" 
   (	"PLAYER_TEACHER_CODE" NUMBER, 
	"PLAYER_CODE" NUMBER, 
	"GROUP_CODE" NUMBER, 
	"PLAYER_TEACHER_TITLE" VARCHAR2(30 BYTE), 
	"PLAYER_TEACHER_CONTENT" VARCHAR2(600 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.PLAYER_TEACHER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PLAYER_TEACHER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."PLAYER_TEACHER_PK" ON "HR"."PLAYER_TEACHER" ("PLAYER_TEACHER_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PLAYER_TEACHER
--------------------------------------------------------

  ALTER TABLE "HR"."PLAYER_TEACHER" ADD CONSTRAINT "PLAYER_TEACHER_PK" PRIMARY KEY ("PLAYER_TEACHER_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."PLAYER_TEACHER" MODIFY ("PLAYER_TEACHER_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_TEACHER" MODIFY ("PLAYER_TEACHER_TITLE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_TEACHER" MODIFY ("GROUP_CODE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_TEACHER" MODIFY ("PLAYER_CODE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_TEACHER" MODIFY ("PLAYER_TEACHER_CODE" NOT NULL ENABLE);
