--------------------------------------------------------
--  颇老捞 积己凳 - 老夸老-5岿-19-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PLAYER_CONTEST
--------------------------------------------------------

  CREATE TABLE "HR"."PLAYER_CONTEST" 
   (	"PLAYER_CONTEST_CODE" NUMBER, 
	"PLAYER_CODE" NUMBER, 
	"GROUP_CODE" NUMBER, 
	"PLAYER_CONTEST_TITLE" VARCHAR2(50 BYTE), 
	"PLAYER_CONTEST_CONTENT" VARCHAR2(600 BYTE), 
	"PLAYER_CONTEST_RESULT" VARCHAR2(50 BYTE), 
	"PLAYER_CONTEST_SHOT" NUMBER, 
	"PLAYER_CONTEST_EFFECTIVESHOT" NUMBER, 
	"PLAYER_CONTEST_GOAL" NUMBER, 
	"PLAYER_CONTEST_ASSIST" NUMBER, 
	"PLAYER_CONTEST_RUNNINGTIME" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.PLAYER_CONTEST
SET DEFINE OFF;
Insert into HR.PLAYER_CONTEST (PLAYER_CONTEST_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_CONTEST_TITLE,PLAYER_CONTEST_CONTENT,PLAYER_CONTEST_RESULT,PLAYER_CONTEST_SHOT,PLAYER_CONTEST_EFFECTIVESHOT,PLAYER_CONTEST_GOAL,PLAYER_CONTEST_ASSIST,PLAYER_CONTEST_RUNNINGTIME) values (63,92,3,' ',' ',' ',0,0,0,0,0);
Insert into HR.PLAYER_CONTEST (PLAYER_CONTEST_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_CONTEST_TITLE,PLAYER_CONTEST_CONTENT,PLAYER_CONTEST_RESULT,PLAYER_CONTEST_SHOT,PLAYER_CONTEST_EFFECTIVESHOT,PLAYER_CONTEST_GOAL,PLAYER_CONTEST_ASSIST,PLAYER_CONTEST_RUNNINGTIME) values (64,93,4,' ',' ',' ',0,0,0,0,0);
Insert into HR.PLAYER_CONTEST (PLAYER_CONTEST_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_CONTEST_TITLE,PLAYER_CONTEST_CONTENT,PLAYER_CONTEST_RESULT,PLAYER_CONTEST_SHOT,PLAYER_CONTEST_EFFECTIVESHOT,PLAYER_CONTEST_GOAL,PLAYER_CONTEST_ASSIST,PLAYER_CONTEST_RUNNINGTIME) values (65,94,5,' ',' ',' ',0,0,0,0,0);
Insert into HR.PLAYER_CONTEST (PLAYER_CONTEST_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_CONTEST_TITLE,PLAYER_CONTEST_CONTENT,PLAYER_CONTEST_RESULT,PLAYER_CONTEST_SHOT,PLAYER_CONTEST_EFFECTIVESHOT,PLAYER_CONTEST_GOAL,PLAYER_CONTEST_ASSIST,PLAYER_CONTEST_RUNNINGTIME) values (66,95,6,' ',' ',' ',0,0,0,0,0);
Insert into HR.PLAYER_CONTEST (PLAYER_CONTEST_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_CONTEST_TITLE,PLAYER_CONTEST_CONTENT,PLAYER_CONTEST_RESULT,PLAYER_CONTEST_SHOT,PLAYER_CONTEST_EFFECTIVESHOT,PLAYER_CONTEST_GOAL,PLAYER_CONTEST_ASSIST,PLAYER_CONTEST_RUNNINGTIME) values (67,96,7,' ',' ',' ',0,0,0,0,0);
Insert into HR.PLAYER_CONTEST (PLAYER_CONTEST_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_CONTEST_TITLE,PLAYER_CONTEST_CONTENT,PLAYER_CONTEST_RESULT,PLAYER_CONTEST_SHOT,PLAYER_CONTEST_EFFECTIVESHOT,PLAYER_CONTEST_GOAL,PLAYER_CONTEST_ASSIST,PLAYER_CONTEST_RUNNINGTIME) values (68,97,8,' ',' ',' ',0,0,0,0,0);
Insert into HR.PLAYER_CONTEST (PLAYER_CONTEST_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_CONTEST_TITLE,PLAYER_CONTEST_CONTENT,PLAYER_CONTEST_RESULT,PLAYER_CONTEST_SHOT,PLAYER_CONTEST_EFFECTIVESHOT,PLAYER_CONTEST_GOAL,PLAYER_CONTEST_ASSIST,PLAYER_CONTEST_RUNNINGTIME) values (61,90,1,' ',' ',' ',0,0,0,0,0);
Insert into HR.PLAYER_CONTEST (PLAYER_CONTEST_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_CONTEST_TITLE,PLAYER_CONTEST_CONTENT,PLAYER_CONTEST_RESULT,PLAYER_CONTEST_SHOT,PLAYER_CONTEST_EFFECTIVESHOT,PLAYER_CONTEST_GOAL,PLAYER_CONTEST_ASSIST,PLAYER_CONTEST_RUNNINGTIME) values (62,91,2,' ',' ',' ',0,0,0,0,0);
Insert into HR.PLAYER_CONTEST (PLAYER_CONTEST_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_CONTEST_TITLE,PLAYER_CONTEST_CONTENT,PLAYER_CONTEST_RESULT,PLAYER_CONTEST_SHOT,PLAYER_CONTEST_EFFECTIVESHOT,PLAYER_CONTEST_GOAL,PLAYER_CONTEST_ASSIST,PLAYER_CONTEST_RUNNINGTIME) values (53,82,1,' ',' ',' ',0,0,0,0,0);
Insert into HR.PLAYER_CONTEST (PLAYER_CONTEST_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_CONTEST_TITLE,PLAYER_CONTEST_CONTENT,PLAYER_CONTEST_RESULT,PLAYER_CONTEST_SHOT,PLAYER_CONTEST_EFFECTIVESHOT,PLAYER_CONTEST_GOAL,PLAYER_CONTEST_ASSIST,PLAYER_CONTEST_RUNNINGTIME) values (54,83,2,' ',' ',' ',0,0,0,0,0);
Insert into HR.PLAYER_CONTEST (PLAYER_CONTEST_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_CONTEST_TITLE,PLAYER_CONTEST_CONTENT,PLAYER_CONTEST_RESULT,PLAYER_CONTEST_SHOT,PLAYER_CONTEST_EFFECTIVESHOT,PLAYER_CONTEST_GOAL,PLAYER_CONTEST_ASSIST,PLAYER_CONTEST_RUNNINGTIME) values (55,84,3,' ',' ',' ',0,0,0,0,0);
Insert into HR.PLAYER_CONTEST (PLAYER_CONTEST_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_CONTEST_TITLE,PLAYER_CONTEST_CONTENT,PLAYER_CONTEST_RESULT,PLAYER_CONTEST_SHOT,PLAYER_CONTEST_EFFECTIVESHOT,PLAYER_CONTEST_GOAL,PLAYER_CONTEST_ASSIST,PLAYER_CONTEST_RUNNINGTIME) values (56,85,4,' ',' ',' ',0,0,0,0,0);
Insert into HR.PLAYER_CONTEST (PLAYER_CONTEST_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_CONTEST_TITLE,PLAYER_CONTEST_CONTENT,PLAYER_CONTEST_RESULT,PLAYER_CONTEST_SHOT,PLAYER_CONTEST_EFFECTIVESHOT,PLAYER_CONTEST_GOAL,PLAYER_CONTEST_ASSIST,PLAYER_CONTEST_RUNNINGTIME) values (57,86,5,' ',' ',' ',0,0,0,0,0);
Insert into HR.PLAYER_CONTEST (PLAYER_CONTEST_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_CONTEST_TITLE,PLAYER_CONTEST_CONTENT,PLAYER_CONTEST_RESULT,PLAYER_CONTEST_SHOT,PLAYER_CONTEST_EFFECTIVESHOT,PLAYER_CONTEST_GOAL,PLAYER_CONTEST_ASSIST,PLAYER_CONTEST_RUNNINGTIME) values (58,87,6,' ',' ',' ',0,0,0,0,0);
Insert into HR.PLAYER_CONTEST (PLAYER_CONTEST_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_CONTEST_TITLE,PLAYER_CONTEST_CONTENT,PLAYER_CONTEST_RESULT,PLAYER_CONTEST_SHOT,PLAYER_CONTEST_EFFECTIVESHOT,PLAYER_CONTEST_GOAL,PLAYER_CONTEST_ASSIST,PLAYER_CONTEST_RUNNINGTIME) values (59,88,7,' ',' ',' ',0,0,0,0,0);
Insert into HR.PLAYER_CONTEST (PLAYER_CONTEST_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_CONTEST_TITLE,PLAYER_CONTEST_CONTENT,PLAYER_CONTEST_RESULT,PLAYER_CONTEST_SHOT,PLAYER_CONTEST_EFFECTIVESHOT,PLAYER_CONTEST_GOAL,PLAYER_CONTEST_ASSIST,PLAYER_CONTEST_RUNNINGTIME) values (60,89,8,' ',' ',' ',0,0,0,0,0);
--------------------------------------------------------
--  DDL for Index CONTEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."CONTEST_PK" ON "HR"."PLAYER_CONTEST" ("PLAYER_CONTEST_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PLAYER_CONTEST
--------------------------------------------------------

  ALTER TABLE "HR"."PLAYER_CONTEST" ADD CONSTRAINT "CONTEST_PK" PRIMARY KEY ("PLAYER_CONTEST_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."PLAYER_CONTEST" MODIFY ("PLAYER_CONTEST_RESULT" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_CONTEST" MODIFY ("PLAYER_CONTEST_TITLE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_CONTEST" MODIFY ("GROUP_CODE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_CONTEST" MODIFY ("PLAYER_CODE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_CONTEST" MODIFY ("PLAYER_CONTEST_CODE" NOT NULL ENABLE);
