--------------------------------------------------------
--  颇老捞 积己凳 - 老夸老-5岿-19-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PLAYER_POSITION
--------------------------------------------------------

  CREATE TABLE "HR"."PLAYER_POSITION" 
   (	"PLAYER_POSITION_CODE" NUMBER, 
	"PLAYER_CODE" NUMBER, 
	"GROUP_CODE" NUMBER, 
	"PLAYER_POSITION_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.PLAYER_POSITION
SET DEFINE OFF;
Insert into HR.PLAYER_POSITION (PLAYER_POSITION_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_POSITION_NAME) values (68,92,3,'0');
Insert into HR.PLAYER_POSITION (PLAYER_POSITION_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_POSITION_NAME) values (69,93,4,'0');
Insert into HR.PLAYER_POSITION (PLAYER_POSITION_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_POSITION_NAME) values (70,94,5,'0');
Insert into HR.PLAYER_POSITION (PLAYER_POSITION_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_POSITION_NAME) values (71,95,6,'0');
Insert into HR.PLAYER_POSITION (PLAYER_POSITION_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_POSITION_NAME) values (72,96,7,'0');
Insert into HR.PLAYER_POSITION (PLAYER_POSITION_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_POSITION_NAME) values (73,97,8,'0');
Insert into HR.PLAYER_POSITION (PLAYER_POSITION_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_POSITION_NAME) values (66,90,1,'0');
Insert into HR.PLAYER_POSITION (PLAYER_POSITION_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_POSITION_NAME) values (67,91,2,'0');
Insert into HR.PLAYER_POSITION (PLAYER_POSITION_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_POSITION_NAME) values (58,82,1,'0');
Insert into HR.PLAYER_POSITION (PLAYER_POSITION_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_POSITION_NAME) values (59,83,2,'0');
Insert into HR.PLAYER_POSITION (PLAYER_POSITION_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_POSITION_NAME) values (60,84,3,'0');
Insert into HR.PLAYER_POSITION (PLAYER_POSITION_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_POSITION_NAME) values (61,85,4,'0');
Insert into HR.PLAYER_POSITION (PLAYER_POSITION_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_POSITION_NAME) values (62,86,5,'0');
Insert into HR.PLAYER_POSITION (PLAYER_POSITION_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_POSITION_NAME) values (63,87,6,'0');
Insert into HR.PLAYER_POSITION (PLAYER_POSITION_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_POSITION_NAME) values (64,88,7,'0');
Insert into HR.PLAYER_POSITION (PLAYER_POSITION_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_POSITION_NAME) values (65,89,8,'0');
--------------------------------------------------------
--  DDL for Index PLAYER_POSITION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."PLAYER_POSITION_PK" ON "HR"."PLAYER_POSITION" ("PLAYER_POSITION_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PLAYER_POSITION
--------------------------------------------------------

  ALTER TABLE "HR"."PLAYER_POSITION" ADD CONSTRAINT "PLAYER_POSITION_PK" PRIMARY KEY ("PLAYER_POSITION_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."PLAYER_POSITION" MODIFY ("GROUP_CODE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_POSITION" MODIFY ("PLAYER_CODE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_POSITION" MODIFY ("PLAYER_POSITION_CODE" NOT NULL ENABLE);
