--------------------------------------------------------
--  파일이 생성됨 - 일요일-5월-19-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PLAYER
--------------------------------------------------------

  CREATE TABLE "HR"."PLAYER" 
   (	"PLAYER_CODE" NUMBER, 
	"GROUP_CODE" NUMBER, 
	"PLAYER_NAME" VARCHAR2(50 BYTE), 
	"PLAYER_TEL" VARCHAR2(50 BYTE), 
	"PLAYER_IMG" BLOB, 
	"PLAYER_EMAIL" VARCHAR2(50 BYTE), 
	"PLAYER_LOCALCODE" NUMBER, 
	"PLAYER_ADDRESS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PLAYER_IMG") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "HR"."PLAYER"."PLAYER_CODE" IS '시퀸스';
REM INSERTING into HR.PLAYER
SET DEFINE OFF;
Insert into HR.PLAYER (PLAYER_CODE,GROUP_CODE,PLAYER_NAME,PLAYER_TEL,PLAYER_EMAIL,PLAYER_LOCALCODE,PLAYER_ADDRESS) values (92,3,'test_team3','0000','test_team3',-1,'test_team3');
Insert into HR.PLAYER (PLAYER_CODE,GROUP_CODE,PLAYER_NAME,PLAYER_TEL,PLAYER_EMAIL,PLAYER_LOCALCODE,PLAYER_ADDRESS) values (93,4,'test_team4','000','test_team4',-1,'test_team4');
Insert into HR.PLAYER (PLAYER_CODE,GROUP_CODE,PLAYER_NAME,PLAYER_TEL,PLAYER_EMAIL,PLAYER_LOCALCODE,PLAYER_ADDRESS) values (94,5,'test_team5','000','test_team5',-1,'test_team5');
Insert into HR.PLAYER (PLAYER_CODE,GROUP_CODE,PLAYER_NAME,PLAYER_TEL,PLAYER_EMAIL,PLAYER_LOCALCODE,PLAYER_ADDRESS) values (95,6,'test_team6','000','test_team6',-1,'test_team6');
Insert into HR.PLAYER (PLAYER_CODE,GROUP_CODE,PLAYER_NAME,PLAYER_TEL,PLAYER_EMAIL,PLAYER_LOCALCODE,PLAYER_ADDRESS) values (96,7,'test_team7','00','test_team7',-1,'test_team7');
Insert into HR.PLAYER (PLAYER_CODE,GROUP_CODE,PLAYER_NAME,PLAYER_TEL,PLAYER_EMAIL,PLAYER_LOCALCODE,PLAYER_ADDRESS) values (90,1,'test_team1','000','team1',-1,'team1');
Insert into HR.PLAYER (PLAYER_CODE,GROUP_CODE,PLAYER_NAME,PLAYER_TEL,PLAYER_EMAIL,PLAYER_LOCALCODE,PLAYER_ADDRESS) values (91,2,'test_team2','000000','test_team2',-1,'test_team2');
Insert into HR.PLAYER (PLAYER_CODE,GROUP_CODE,PLAYER_NAME,PLAYER_TEL,PLAYER_EMAIL,PLAYER_LOCALCODE,PLAYER_ADDRESS) values (97,8,'test_team8','000','test_team8',-1,'test_team8');
Insert into HR.PLAYER (PLAYER_CODE,GROUP_CODE,PLAYER_NAME,PLAYER_TEL,PLAYER_EMAIL,PLAYER_LOCALCODE,PLAYER_ADDRESS) values (82,1,'라보스','02112','라보스@naver.com',0,'서울동대문');
Insert into HR.PLAYER (PLAYER_CODE,GROUP_CODE,PLAYER_NAME,PLAYER_TEL,PLAYER_EMAIL,PLAYER_LOCALCODE,PLAYER_ADDRESS) values (83,2,'메에시','062112','메에시@lycos.co.kr',-1,'전남 화순읍');
Insert into HR.PLAYER (PLAYER_CODE,GROUP_CODE,PLAYER_NAME,PLAYER_TEL,PLAYER_EMAIL,PLAYER_LOCALCODE,PLAYER_ADDRESS) values (84,3,'싸울라','062112','싸울라@gmail.com',2,'광주 서문대로');
Insert into HR.PLAYER (PLAYER_CODE,GROUP_CODE,PLAYER_NAME,PLAYER_TEL,PLAYER_EMAIL,PLAYER_LOCALCODE,PLAYER_ADDRESS) values (85,4,'다비드초코바','08112','초코마@naver.com',-1,'경기도 철원');
Insert into HR.PLAYER (PLAYER_CODE,GROUP_CODE,PLAYER_NAME,PLAYER_TEL,PLAYER_EMAIL,PLAYER_LOCALCODE,PLAYER_ADDRESS) values (86,5,'핫바','05112','핫바@hotmail.com',7,'제주아일랜드');
Insert into HR.PLAYER (PLAYER_CODE,GROUP_CODE,PLAYER_NAME,PLAYER_TEL,PLAYER_EMAIL,PLAYER_LOCALCODE,PLAYER_ADDRESS) values (87,6,'리흐토','002','리호토@naver.com',-1,'만리장성시');
Insert into HR.PLAYER (PLAYER_CODE,GROUP_CODE,PLAYER_NAME,PLAYER_TEL,PLAYER_EMAIL,PLAYER_LOCALCODE,PLAYER_ADDRESS) values (88,7,'송흥민','05112','흥민@우리형.com',-1,'흥민시');
Insert into HR.PLAYER (PLAYER_CODE,GROUP_CODE,PLAYER_NAME,PLAYER_TEL,PLAYER_EMAIL,PLAYER_LOCALCODE,PLAYER_ADDRESS) values (89,8,'물날두','02112','호우@날.두',-1,'전북 아르헨티나시');
--------------------------------------------------------
--  DDL for Index PLAYER_MANAGER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."PLAYER_MANAGER_PK" ON "HR"."PLAYER" ("PLAYER_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PLAYER
--------------------------------------------------------

  ALTER TABLE "HR"."PLAYER" ADD CONSTRAINT "PLAYER_MANAGER_PK" PRIMARY KEY ("PLAYER_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."PLAYER" MODIFY ("PLAYER_LOCALCODE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER" MODIFY ("PLAYER_TEL" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER" MODIFY ("PLAYER_NAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER" MODIFY ("GROUP_CODE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER" MODIFY ("PLAYER_CODE" NOT NULL ENABLE);
