--------------------------------------------------------
--  파일이 생성됨 - 일요일-5월-19-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PLAYER_MEDICAL
--------------------------------------------------------

  CREATE TABLE "HR"."PLAYER_MEDICAL" 
   (	"PLAYER_MEDICAL_CODE" NUMBER, 
	"PLAYER_CODE" NUMBER, 
	"GROUP_CODE" NUMBER, 
	"PLAYER_MEDICAL_PERIOD" NUMBER, 
	"PLAYER_MEDICAL_TITLE" VARCHAR2(30 BYTE), 
	"PLAYER_MEDICAL_CONTENT" VARCHAR2(600 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HR"."PLAYER_MEDICAL"."PLAYER_MEDICAL_CODE" IS '시퀸스';
REM INSERTING into HR.PLAYER_MEDICAL
SET DEFINE OFF;
Insert into HR.PLAYER_MEDICAL (PLAYER_MEDICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_MEDICAL_PERIOD,PLAYER_MEDICAL_TITLE,PLAYER_MEDICAL_CONTENT) values (49,92,3,0,' ',' ');
Insert into HR.PLAYER_MEDICAL (PLAYER_MEDICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_MEDICAL_PERIOD,PLAYER_MEDICAL_TITLE,PLAYER_MEDICAL_CONTENT) values (50,93,4,0,' ',' ');
Insert into HR.PLAYER_MEDICAL (PLAYER_MEDICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_MEDICAL_PERIOD,PLAYER_MEDICAL_TITLE,PLAYER_MEDICAL_CONTENT) values (51,94,5,0,' ',' ');
Insert into HR.PLAYER_MEDICAL (PLAYER_MEDICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_MEDICAL_PERIOD,PLAYER_MEDICAL_TITLE,PLAYER_MEDICAL_CONTENT) values (52,95,6,0,' ',' ');
Insert into HR.PLAYER_MEDICAL (PLAYER_MEDICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_MEDICAL_PERIOD,PLAYER_MEDICAL_TITLE,PLAYER_MEDICAL_CONTENT) values (53,96,7,0,' ',' ');
Insert into HR.PLAYER_MEDICAL (PLAYER_MEDICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_MEDICAL_PERIOD,PLAYER_MEDICAL_TITLE,PLAYER_MEDICAL_CONTENT) values (54,97,8,0,' ',' ');
Insert into HR.PLAYER_MEDICAL (PLAYER_MEDICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_MEDICAL_PERIOD,PLAYER_MEDICAL_TITLE,PLAYER_MEDICAL_CONTENT) values (47,90,1,0,' ',' ');
Insert into HR.PLAYER_MEDICAL (PLAYER_MEDICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_MEDICAL_PERIOD,PLAYER_MEDICAL_TITLE,PLAYER_MEDICAL_CONTENT) values (48,91,2,0,' ',' ');
Insert into HR.PLAYER_MEDICAL (PLAYER_MEDICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_MEDICAL_PERIOD,PLAYER_MEDICAL_TITLE,PLAYER_MEDICAL_CONTENT) values (39,82,1,0,' ',' ');
Insert into HR.PLAYER_MEDICAL (PLAYER_MEDICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_MEDICAL_PERIOD,PLAYER_MEDICAL_TITLE,PLAYER_MEDICAL_CONTENT) values (40,83,2,0,' ',' ');
Insert into HR.PLAYER_MEDICAL (PLAYER_MEDICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_MEDICAL_PERIOD,PLAYER_MEDICAL_TITLE,PLAYER_MEDICAL_CONTENT) values (41,84,3,0,' ',' ');
Insert into HR.PLAYER_MEDICAL (PLAYER_MEDICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_MEDICAL_PERIOD,PLAYER_MEDICAL_TITLE,PLAYER_MEDICAL_CONTENT) values (42,85,4,0,' ',' ');
Insert into HR.PLAYER_MEDICAL (PLAYER_MEDICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_MEDICAL_PERIOD,PLAYER_MEDICAL_TITLE,PLAYER_MEDICAL_CONTENT) values (43,86,5,0,' ',' ');
Insert into HR.PLAYER_MEDICAL (PLAYER_MEDICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_MEDICAL_PERIOD,PLAYER_MEDICAL_TITLE,PLAYER_MEDICAL_CONTENT) values (44,87,6,0,' ',' ');
Insert into HR.PLAYER_MEDICAL (PLAYER_MEDICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_MEDICAL_PERIOD,PLAYER_MEDICAL_TITLE,PLAYER_MEDICAL_CONTENT) values (45,88,7,0,' ',' ');
Insert into HR.PLAYER_MEDICAL (PLAYER_MEDICAL_CODE,PLAYER_CODE,GROUP_CODE,PLAYER_MEDICAL_PERIOD,PLAYER_MEDICAL_TITLE,PLAYER_MEDICAL_CONTENT) values (46,89,8,0,' ',' ');
--------------------------------------------------------
--  DDL for Index PLAYER_MEDICAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."PLAYER_MEDICAL_PK" ON "HR"."PLAYER_MEDICAL" ("PLAYER_MEDICAL_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PLAYER_MEDICAL
--------------------------------------------------------

  ALTER TABLE "HR"."PLAYER_MEDICAL" ADD CONSTRAINT "PLAYER_MEDICAL_PK" PRIMARY KEY ("PLAYER_MEDICAL_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."PLAYER_MEDICAL" MODIFY ("PLAYER_MEDICAL_CODE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_MEDICAL" MODIFY ("PLAYER_MEDICAL_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_MEDICAL" MODIFY ("PLAYER_MEDICAL_TITLE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_MEDICAL" MODIFY ("PLAYER_MEDICAL_PERIOD" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_MEDICAL" MODIFY ("GROUP_CODE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLAYER_MEDICAL" MODIFY ("PLAYER_CODE" NOT NULL ENABLE);
